import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
            <nav className="bg-green-800 flex justify-center py-2">
              <ul className="flex justify-center gap-5 text-white text-lg font-bold">
                <li>
                  Home
                </li>
                <li>
                  Shop
                </li>
                <li>
                  About 
                </li>
                <li>
                  Contact
                </li>
              </ul>
            </nav>
        </header>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
